### ISSUE TITLE
1. Análisis y diseño

### ISSUE THREAD

**Issue by JoelPulidoG** [ISWPOLI/old_school#8]
**Descripción**
Esta sección contiene los procesos relacionados con el proceso de análisis y diseño del proyecto

**Tareas**
- [x] Diagrama de casos de uso
- [x] Diagramas de clase
- [x] Diagramas de secuencia

**Comment by mpcamacho1** [comment]
[Fichas.Casos.de.Uso.pdf](https://github.com/ISWPOLI/old_school/files/1443757/Fichas.Casos.de.Uso.pdf)

[Modelado.Casos.de.uso.pdf](https://github.com/ISWPOLI/old_school/files/1443756/Modelado.Casos.de.uso.pdf)
Se adjuntan diseño de diagramas de casos de uso del sistema y diagramas de clase.
![diagramasdeclases](https://user-images.githubusercontent.com/31083627/32411905-9b89b0ba-c1b5-11e7-8cd3-bd61bbcfa06e.jpg)

**Comment by amdiazbe** [comment]
![modulo login](https://user-images.githubusercontent.com/30843838/32703771-aedcfeb0-c7c8-11e7-8d3b-cddc5964bcec.jpg)
![modulo nuevo proyecto](https://user-images.githubusercontent.com/30843838/32703772-aef7558a-c7c8-11e7-97e3-ce7c7bc99b16.jpg)
![modulo busqueda](https://user-images.githubusercontent.com/30843838/32703773-af0dfbb4-c7c8-11e7-94e0-3c9ecccde1d2.jpg)
![modulo descarga de archivos](https://user-images.githubusercontent.com/30843838/32703774-af233132-c7c8-11e7-9d88-26b13a18937d.jpg)
![modulo de carga de archivos](https://user-images.githubusercontent.com/30843838/32703802-1c74bb66-c7c9-11e7-8377-a26c009274c0.jpeg)
